// <auto-generated />
namespace Saned.ArousQatar.Data.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class FavoriteGetAll : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FavoriteGetAll));
        
        string IMigrationMetadata.Id
        {
            get { return "201611271008550_FavoriteGetAll"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
