// <auto-generated />
namespace Saned.ArousQatar.Data.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class createAdPriceGetAllSP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createAdPriceGetAllSP));
        
        string IMigrationMetadata.Id
        {
            get { return "201701311038202_createAdPriceGetAllSP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
