//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Advertisment()
        {
            this.AdvertismentImages = new HashSet<AdvertismentImage>();
            this.Comments = new HashSet<Comment>();
            this.Complaints = new HashSet<Complaint>();
            this.Favorites = new HashSet<Favorite>();
            this.Likes = new HashSet<Like>();
        }
    
        public int Id { get; set; }
        public bool IsPaided { get; set; }
        public string Description { get; set; }
        public int NumberOfViews { get; set; }
        public int NumberOfLikes { get; set; }
        public Nullable<decimal> PaidEdPrice { get; set; }
        public Nullable<bool> IsArchieved { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int CategoryId { get; set; }
        public string ApplicationUserId { get; set; }
        public Nullable<int> AdvertismentPriceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvertismentImage> AdvertismentImages { get; set; }
        public virtual AdvertismentPrice AdvertismentPrice { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint> Complaints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Like> Likes { get; set; }
    }
}
