//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int AdvertismentId { get; set; }
        public string ApplicationUserId { get; set; }
    
        public virtual Advertisment Advertisment { get; set; }
    }
}
