//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Saned_ArousQatarEntities : DbContext
    {
        public Saned_ArousQatarEntities()
            : base("name=Saned_ArousQatarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdvertismentImage> AdvertismentImages { get; set; }
        public virtual DbSet<AdvertismentPrice> AdvertismentPrices { get; set; }
        public virtual DbSet<Advertisment> Advertisments { get; set; }
        public virtual DbSet<BankAccount> BankAccounts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Complaint> Complaints { get; set; }
        public virtual DbSet<ContactInformation> ContactInformations { get; set; }
        public virtual DbSet<ContactType> ContactTypes { get; set; }
        public virtual DbSet<EmailSetting> EmailSettings { get; set; }
        public virtual DbSet<Error> Errors { get; set; }
        public virtual DbSet<Favorite> Favorites { get; set; }
        public virtual DbSet<Like> Likes { get; set; }
        public virtual DbSet<RefreshToken> RefreshTokens { get; set; }
    }
}
